import {
  AppWindow,
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Circle,
  Cloud,
  Coffee,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Film,
  Fuel,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HeartPulse,
  House,
  Key,
  KeyRound,
  Landmark,
  Laptop,
  Music,
  Palette,
  PartyPopper,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Puzzle,
  Receipt,
  Repeat,
  Server,
  Shield,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Icone assegnabili a tipi di servizio e categorie (nome lucide salvato nel database).
export const ICONE: Record<string, LucideIcon> = {
  globe: Globe,
  server: Server,
  puzzle: Puzzle,
  cloud: Cloud,
  repeat: Repeat,
  shield: Shield,
  landmark: Landmark,
  ellipsis: Ellipsis,
  "app-window": AppWindow,
  laptop: Laptop,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  house: House,
  "shopping-cart": ShoppingCart,
  car: Car,
  "heart-pulse": HeartPulse,
  "party-popper": PartyPopper,
  "key-round": KeyRound,
  key: Key,
  zap: Zap,
  utensils: Utensils,
  coffee: Coffee,
  plane: Plane,
  bus: Bus,
  fuel: Fuel,
  gift: Gift,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  music: Music,
  film: Film,
  tv: Tv,
  phone: Phone,
  smartphone: Smartphone,
  wifi: Wifi,
  shirt: Shirt,
  baby: Baby,
  "paw-print": PawPrint,
  pill: Pill,
  wrench: Wrench,
  hammer: Hammer,
  palette: Palette,
  receipt: Receipt,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  target: Target,
  "credit-card": CreditCard,
  banknote: Banknote,
  wallet: Wallet,
  sparkles: Sparkles,
};

/** Nomi delle icone proposte nel selettore delle categorie, in ordine. */
export const NOMI_ICONE_CATEGORIE = Object.keys(ICONE);

export function icona(nome: string | null | undefined): LucideIcon {
  return (nome && ICONE[nome]) || Circle;
}
